### ISSUE TITLE
504 Gateway

### ISSUE THREAD

**Issue by YasmijnVels** [systembee/sysb.AI#19]
is there is a problem with the server?

![image](https://user-images.githubusercontent.com/59023524/75326367-c30ec180-587a-11ea-91aa-5a5a4984c8be.png)

**Comment by jorbig** [comment]
It seems there is: I'm facing the same problem. I hope situations like this will be rare.

**Comment by YasmijnVels** [comment]
yesterday it was already and now again.
hope it will be solved soon!

**Comment by YasmijnVels** [comment]
@systembee can u solve the problem?

**Comment by systembee** [comment]
@YasmijnVels @jorbig Thanks for notifying us. We have made some changes to HTTPS config, Could you please let me know if the issue you are facing is only related to HTTPS or HTTP is also impacted.

If it is frequent then we will revert the change.

**Comment by YasmijnVels** [comment]
@systembee Both http and https don't work

**Comment by YasmijnVels** [comment]
@systembee is it also possible to use your own domain name? with your service?

**Comment by YasmijnVels** [comment]
@systembee is the problem solved?

**Comment by YasmijnVels** [comment]
and my api system also has problems posting to discord. by those changes
https://lunabotlist.eu.sysb.ai/api/bots/list

**Comment by YasmijnVels** [comment]
http is working 
https is not working
@systembee

**Comment by systembee** [comment]
@YasmijnVels What was the error while API system was posting? Now we have reverted the change, Apologies for the inconvenience.

Please let me know if things looks good.

**Comment by YasmijnVels** [comment]
now is the problem solve thanks 
the api system is also working now on https and website to
![image](https://user-images.githubusercontent.com/59023524/75373132-fc225280-58c9-11ea-9128-c1bffd88c8f2.png)

**Comment by systembee** [comment]
@YasmijnVels Thanks for confirming, I am closing this issue
